### ISSUE TITLE
hardcoded dependency to xip.io for keptn event broker

### ISSUE THREAD

**Issue by akirasoft** [keptn/github-service#3]
I do not use xip.io, so as a user I would like to be able to specify the full url for the istio ingress gateway. 

      const eventBrokerUri = `event-broker-ext.keptn.` +
        `${istioIngressGatewayService.body.status.loadBalancer.ingress[0].ip}.xip.io`;

**Comment by akirasoft** [comment]
additionally, in my cluster, the istio ingress gateway IP is null and I am utilizing the hostname instead.

**Comment by johannes-b** [comment]
I close this issue since it it documented and addressed here: https://github.com/keptn/keptn/issues/283
